kind = "web"
previewPath = "/"
title = "Nepal College Website"
version = "1.0.0"
id = "artifacts/college-website"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 22951
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/college-website run dev"

[services.env]
PORT = "22951"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/college-website", "run", "build"]
publicDir = "artifacts/college-website/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
